### ISSUE TITLE
Unable to Copy & Paste Measures with Dynamic Formatting Applied

### ISSUE THREAD

**Issue by PBIQueryous** [TabularEditor/TabularEditor#1099]
!!! Please make sure you're using the latest version of Tabular Editor 2.X before submitting a bug !!!
!!! For Tabular Editor 3 issues, go here -> https://github.com/TabularEditor/TabularEditor3/issues !!!

**Describe the bug**
There appears to be an issue when copying and pasting measures in TE2 where **new Dynamic Formatting** is applied. 
The error message reads: "Unhandled exception has occured in your application".

**To Reproduce**
1. Open PowerBI
2. Create a new measure of your choosing
3. Navigate to ribbon, click on "Measure Tools"
4. Navigate to "Format" dropdown selection. Choose "Dynamic"
5. Navigate to "External Tools". Open TE2.
6. Navigate to folders on Left-hand pane
7. Click on "Tables" folder, and search for the newly created measure (with Dynamic Formatting)
8. Copy and Paste (Ctrl+C / Ctrl+V)
9. See error

**Expected behavior**
The copy and paste action should result in the successful duplication of the selected measure.

**Observed behavior**
The copy and paste action results in an error message. It also causes the programme to crash, so no subsequent actions work. Please see below:

![image](https://user-images.githubusercontent.com/95970959/235732850-0707f943-e75a-4c00-80c1-479381c2796e.png)

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
Microsoft.AnalysisServices.Tabular.TomInternalException: An internal error has occured.
   at Microsoft.AnalysisServices.Tabular.Measure.SerializeToJsonObject(JsonObject result, SerializeOptions options, CompatibilityMode mode, Int32 dbCompatibilityLevel)
   at Microsoft.AnalysisServices.Tabular.JsonSerializer.SerializeObjectImpl(MetadataObject metadataObject, SerializeOptions options, Int32 dbCompatibilityLevel, CompatibilityMode mode)
   at Microsoft.AnalysisServices.Tabular.JsonSerializer.SerializeObject(MetadataObject metadataObject, SerializeOptions options)
   at TabularEditor.TOMWrapper.Undo.UndoAddRemoveAction..ctor(ITabularObjectCollection collection, TabularNamedObject obj, UndoAddRemoveActionType actionType)
   at TabularEditor.TOMWrapper.TabularObjectCollection`1.InternalAdd(T item)
   at TabularEditor.TOMWrapper.Measure.CreateFromMetadata(Table parent, Measure metadataObject)
   at TabularEditor.TOMWrapper.Serialization.Serializer.DeserializeMeasure(JObject json, Table target)
   at TabularEditor.TOMWrapper.TabularCommonActions.InsertObjects(ObjectJsonContainer objectContainer, ITabularNamedObject destination)
   at TabularEditor.UI.Actions.PasteAction.OnExecute(EventArgs e)
   at Crad.Windows.Forms.Actions.Action.DoExecute()
   at Crad.Windows.Forms.Actions.Action.target_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripMenuItem.ProcessCmdKey(Message& m, Keys keyData)
   at System.Windows.Forms.ToolStripManager.ProcessShortcut(Message& m, Keys shortcut)
   at System.Windows.Forms.ToolStripManager.ProcessCmdKey(Message& m, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Form.ProcessCmdKey(Message& msg, Keys keyData)
   at TabularEditor.FormMain.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4614.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
TabularEditor
    Assembly Version: 2.18.8503.15415
    Win32 Version: 2.18.8503.15415
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/TabularEditor.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
TOMWrapper
    Assembly Version: 2.18.8503.15415
    Win32 Version: 2.18.8503.15415
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/TabularEditor.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4550.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.AnalysisServices.Core
    Assembly Version: 19.61.1.4
    Win32 Version: 16.0.77.22
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/Microsoft.AnalysisServices.Core.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4584.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Microsoft.AnalysisServices.SPClient.Interfaces
    Assembly Version: 19.61.1.4
    Win32 Version: 16.0.77.22
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/Microsoft.AnalysisServices.SPClient.Interfaces.DLL
----------------------------------------
Microsoft.AnalysisServices.Tabular
    Assembly Version: 19.61.1.4
    Win32 Version: 16.0.77.22
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/Microsoft.AnalysisServices.Tabular.DLL
----------------------------------------
Microsoft.AnalysisServices.Tabular.Json
    Assembly Version: 19.61.1.4
    Win32 Version: 16.0.77.22
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/Microsoft.AnalysisServices.Tabular.Json.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Microsoft.AnalysisServices.Tabular.Tmdl
    Assembly Version: 19.61.1.4
    Win32 Version: 16.0.77.22
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/Microsoft.AnalysisServices.Tabular.Tmdl.DLL
----------------------------------------
Microsoft.Identity.Client
    Assembly Version: 4.52.0.0
    Win32 Version: 4.52.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/Microsoft.Identity.Client.DLL
----------------------------------------
Microsoft.IdentityModel.Abstractions
    Assembly Version: 6.28.1.0
    Win32 Version: 6.28.1.40403
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/Microsoft.IdentityModel.Abstractions.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ValueTuple/v4.0_4.0.0.0__cc7b13ffcd2ddd51/System.ValueTuple.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 2.18.8503.15415
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/TabularEditor.exe
----------------------------------------
System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
FastColoredTextBox
    Assembly Version: 2.16.24.0
    Win32 Version: 2.18.8503.15415
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/TabularEditor.exe
----------------------------------------
Crad.Windows.Forms.Actions
    Assembly Version: 1.3.0.0
    Win32 Version: 2.18.8503.15415
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/TabularEditor.exe
----------------------------------------
Antlr4.Runtime
    Assembly Version: 4.6.0.0
    Win32 Version: 2.18.8503.15415
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/TabularEditor.exe
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
dtaza3x4
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
Microsoft.WindowsAPICodePack
    Assembly Version: 1.1.2.0
    Win32 Version: 2.18.8503.15415
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/TabularEditor.exe
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4435.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Application specifics**
 - Tabular Editor 2.18.1
 
![image](https://user-images.githubusercontent.com/95970959/235733967-f3c98fe0-6856-4f1c-9690-3850a2496983.png)

 - Semantic Engine used: PowerBI Desktop
 - Model Compatibility Level: 1601

**Additional context**
I have been able to isolate the issue and it definitely only occurs once Dynamic Formatting is applied. Currently, when Dynamic Formatting is applied, the "Format String" field in TE2 appears empty. This may be part of the issue. There are no visible indicators to say that Dynamic Formatting is applied.

**Comment by otykier** [comment]
Thanks for reporting. It turns out this issue exists in TE 3 as well. We're investigating!

**Comment by otykier** [comment]
For TE2, this is now fixed in [version 2.18.2](https://github.com/TabularEditor/TabularEditor/releases/tag/2.18.2).

For TE3, this is now fixed in [version 3.17.1](https://docs.tabulareditor.com/te3/other/release-notes/3_7_1.html?tabs=downloads).
