### ISSUE TITLE
Can't save down Model opened from DB as a local .bim file

### ISSUE THREAD

**Issue by renlycat** [TabularEditor/TabularEditor#1168]
Getting "Newtonsoft.Json.JsonException: Cannot add or remove items from Newtonsoft.Json.Linq.JProperty." when trying to save a model locally after opening it from the server.  This looks like the same as issue #1023.

**Steps to reproduce the behavior** (same as #1023):
1. File -> Open -> From DB
2. File -> Save As
3. Click in the dialog on the existing Model.bim file as we want to overwrite this file with the version from the DB.  Also happens if save as a new filename.
4. Click on Save.
You'll get the exception.

**Expected behavior**
Model successfully saved down into local .bim file.

**Observed behavior**
Here is the full stack trace from the error popup:
```
Newtonsoft.Json.JsonException: Cannot add or remove items from Newtonsoft.Json.Linq.JProperty.
   at TabularEditor.UI.UIController.HandleError(String operationTitle, Exception e)
   at TabularEditor.UI.UIController.File_SaveAs()
   at TabularEditor.FormMain.actSaveAs_Execute(Object sender, EventArgs e)
   at Crad.Windows.Forms.Actions.Action.OnExecute(EventArgs e)
   at TabularEditor.UI.UIModelAction.OnExecute(EventArgs e)
   at Crad.Windows.Forms.Actions.Action.DoExecute()
   at Crad.Windows.Forms.Actions.Action.target_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
TabularEditor
    Assembly Version: 2.21.8716.40411
    Win32 Version: 2.21.8716.40411
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/TabularEditor.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9206.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
TOMWrapper
    Assembly Version: 2.21.8716.40410
    Win32 Version: 2.21.8716.40411
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/TabularEditor.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9200.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.AnalysisServices.Core
    Assembly Version: 19.69.6.2
    Win32 Version: 16.0.108.20
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/Microsoft.AnalysisServices.Core.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9191.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Microsoft.AnalysisServices.SPClient.Interfaces
    Assembly Version: 19.69.6.2
    Win32 Version: 16.0.108.20
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/Microsoft.AnalysisServices.SPClient.Interfaces.DLL
----------------------------------------
Microsoft.AnalysisServices.Tabular
    Assembly Version: 19.69.6.2
    Win32 Version: 16.0.108.20
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/Microsoft.AnalysisServices.Tabular.DLL
----------------------------------------
Microsoft.AnalysisServices.Tabular.Json
    Assembly Version: 19.69.6.2
    Win32 Version: 16.0.108.20
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/Microsoft.AnalysisServices.Tabular.Json.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Microsoft.AnalysisServices.Tabular.Tmdl
    Assembly Version: 19.69.6.2
    Win32 Version: 16.0.108.20
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/Microsoft.AnalysisServices.Tabular.Tmdl.DLL
----------------------------------------
Microsoft.Identity.Client
    Assembly Version: 4.57.0.0
    Win32 Version: 4.57.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/Microsoft.Identity.Client.DLL
----------------------------------------
Microsoft.IdentityModel.Abstractions
    Assembly Version: 7.0.3.0
    Win32 Version: 7.0.3.41017
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/Microsoft.IdentityModel.Abstractions.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.dll
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.ValueTuple/v4.0_4.0.0.0__cc7b13ffcd2ddd51/System.ValueTuple.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 2.21.8716.40411
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/TabularEditor.exe
----------------------------------------
System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
FastColoredTextBox
    Assembly Version: 2.16.24.0
    Win32 Version: 2.21.8716.40411
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/TabularEditor.exe
----------------------------------------
Crad.Windows.Forms.Actions
    Assembly Version: 1.3.0.0
    Win32 Version: 2.21.8716.40411
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/TabularEditor.exe
----------------------------------------
Antlr4.Runtime
    Assembly Version: 4.6.0.0
    Win32 Version: 2.21.8716.40411
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/TabularEditor.exe
----------------------------------------
Microsoft.WindowsAPICodePack
    Assembly Version: 1.1.2.0
    Win32 Version: 2.21.8716.40411
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/TabularEditor.exe
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Microsoft.WindowsAPICodePack.Shell
    Assembly Version: 1.1.0.0
    Win32 Version: 2.21.8716.40411
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/TabularEditor.exe
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9200.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9200.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9200.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9200.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------

```

**Application specifics**
 - Tabular Editor 2.X version: 2.21.0
 - Semantic Engine used: SSAS 2019
 - Model Compatibility Level: 1500

**Additional context**
Note that i'm running the latest version as of 11/23/2023.

**Comment by otykier** [comment]
I'm unfortunately not able to reproduce this error. Unfortunately, the `TabularEditor.UI.UIController.HandleError(String operationTitle, Exception e)` line, hides the actual stack trace from where the error originates, so this could be a different error than #1023, even though the reported stack trace looks similar.

Are you able to save the model as a folder structure instead (File > Save to Folder...)? Alternatively, could you try to create the Model.bim file through Visual Studio's "Import from Server (Tabular)" option. It you manage to save the file that way, it would be helpful if you could send us the Model.bim file at support@tabulareditor.com, so we can take a closer look. Thanks!

**Comment by renlycat** [comment]
Thanks.  Save to Folder works fine, just saving down the bim file does not.    My usual tactic is to create a new VS project via Import from Server and get it from there.  It works but a much bigger pain.

I'll try to send through the model but i might need to scrub it a bit.  I'm in a heavily-regulated industry and want to make it Compliance-safe.

**Comment by otykier** [comment]
@renlycat have you been able to create a minimal model you can share with us, that reproduces this issue?

**Comment by Machestro** [comment]
I have the same issue. For my case the solution is: 
1. save model to folder (json serialization) 
2. open saved model from folder
3. save model as bim
4. open bim model
5. deploy model to server
6. proccess cube
and now TE allow to save problem cube
