### ISSUE TITLE
Object dependencies run out of memory (endless loop?), Tabular Editor Crash 

### ISSUE THREAD

**Issue by fmms** [TabularEditor/TabularEditor#1173]
**Describe the bug**
I have a Tabular Data model with several hundred measures and a hundred tables. 
My machine has plenty of memory -- 16 GB.

However, the "Show objects on which [asd] depend", results in out of memory. The "Show objects that depend on [asd]" seems to work.

Unfortunately I cannot share the full model and have no idea how to narrow down the problem yet.

**To Reproduce**
1. Go to any medium complex measure
2. Press F3
3.  Click the radio box "show objects on which [asd] depend"

**Expected behavior**
I get the dependency tree.

**Observed behavior**
Program crashes:
![image](https://github.com/TabularEditor/TabularEditor/assets/908734/b36ed5aa-7113-4954-a970-8c6750aa1455)

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.String.Concat(String str0, String str1, String str2)
   at TabularEditor.UI.UIDeleteAction.OnUpdate(EventArgs e)
   at Crad.Windows.Forms.Actions.Action.DoUpdate()
   at Crad.Windows.Forms.Actions.ActionList.OnUpdate(EventArgs eventArgs)
   at Crad.Windows.Forms.Actions.ActionList.Application_Idle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.RunDialog(Form form)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at System.Windows.Forms.Form.ShowDialog()
   at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)
   at System.Windows.Forms.Control.WndProcException(Exception e)
   at System.Windows.Forms.Control.ControlNativeWindow.OnThreadException(Exception e)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.SendMessage(HandleRef hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.Control.SendMessage(Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.Control.ReflectMessageInternal(IntPtr hWnd, Message& m)
   at System.Windows.Forms.Control.WmNotify(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
TabularEditor
    Assembly Version: 2.22.8784.24138
    Win32 Version: 2.22.8784.24138
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/TabularEditor.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9214.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
TOMWrapper
    Assembly Version: 2.22.8784.24134
    Win32 Version: 2.22.8784.24138
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/TabularEditor.exe
----------------------------------------
Microsoft.AnalysisServices.Tabular
    Assembly Version: 19.74.2.0
    Win32 Version: 16.0.117.17
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/Microsoft.AnalysisServices.Tabular.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9214.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.AnalysisServices.Core
    Assembly Version: 19.74.2.0
    Win32 Version: 16.0.117.17
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/Microsoft.AnalysisServices.Core.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9214.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Microsoft.AnalysisServices.SPClient.Interfaces
    Assembly Version: 19.74.2.0
    Win32 Version: 16.0.117.17
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/Microsoft.AnalysisServices.SPClient.Interfaces.DLL
----------------------------------------
Microsoft.AnalysisServices.Tabular.Json
    Assembly Version: 19.74.2.0
    Win32 Version: 16.0.117.17
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/Microsoft.AnalysisServices.Tabular.Json.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Microsoft.Identity.Client
    Assembly Version: 4.58.1.0
    Win32 Version: 4.58.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/Microsoft.Identity.Client.DLL
----------------------------------------
Microsoft.IdentityModel.Abstractions
    Assembly Version: 7.2.0.0
    Win32 Version: 7.2.0.50110
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/Microsoft.IdentityModel.Abstractions.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Buffers
    Assembly Version: 4.0.3.0
    Win32 Version: 4.6.28619.01
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/System.Buffers.DLL
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 7.0.0.2
    Win32 Version: 7.0.423.11508
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/System.Diagnostics.DiagnosticSource.DLL
----------------------------------------
System.IO.Compression
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.dll
----------------------------------------
System.Memory
    Assembly Version: 4.0.1.2
    Win32 Version: 4.6.31308.01
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/System.Memory.DLL
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 4.1.4.0
    Win32 Version: 4.6.26515.06
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/System.Numerics.Vectors.DLL
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.21.52210
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 2.22.8784.24138
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/TabularEditor.exe
----------------------------------------
System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
FastColoredTextBox
    Assembly Version: 2.16.24.0
    Win32 Version: 2.22.8784.24138
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/TabularEditor.exe
----------------------------------------
Crad.Windows.Forms.Actions
    Assembly Version: 1.3.0.0
    Win32 Version: 2.22.8784.24138
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/TabularEditor.exe
----------------------------------------
Antlr4.Runtime
    Assembly Version: 4.6.0.0
    Win32 Version: 2.22.8784.24138
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/TabularEditor.exe
----------------------------------------
Microsoft.WindowsAPICodePack
    Assembly Version: 1.1.2.0
    Win32 Version: 2.22.8784.24138
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/TabularEditor.exe
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Microsoft.WindowsAPICodePack.Shell
    Assembly Version: 1.1.0.0
    Win32 Version: 2.22.8784.24138
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/TabularEditor.exe
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Application specifics**
 - Tabular Editor 2.X version: 2.22
 - Semantic Engine used: SSAS 2019
 - Model Compatibility Level: 1500

**Additional context**

**Comment by fmms** [comment]
@otykier  is the recursion depth limited at the moment?
Is there any C# script that I could use to identify measures that are the issue?

**Comment by otykier** [comment]
I'm unfortunately not able to reproduce this. It would be helpful if you could answer the following:

- Is this issue specific to one particular model, or can you reproduce it with other models?
- If it's only one specific model, does it happen to all measures, or only specific ones?
- Does the stack trace look similar each time? (Specifically, do you see the line `at TabularEditor.UI.UIDeleteAction.OnUpdate(EventArgs e)` near the top of each stack trace?)

Thanks!

**Comment by fmms** [comment]
Hi @otykier thanks for the response regarding your responses.

- This is with one specific Model, though I think, I have seen it on another project before as well...
- In this model it is specific to some -- though lots of measures.
- The stack trace appears to be random. I click on `Show objects on which [asd] depend` it takes about two minutes for an out of memory exception to appear, when clicking "Continue" in these dialogs the next out of memory appears in just a fraction of a second.
- Another remark. Tabular Editor consumes about 800 Megabyte at the time of out of memory. However, there is still 3 GB of memory left. 

Have a look at the following screenshot:
![image](https://github.com/TabularEditor/TabularEditor/assets/908734/d77ae9a8-e17f-45ec-8d66-ca5e6eec79ea)

**Comment by fmms** [comment]
@otykier i have the feeling that it does not depend on the specific measure selected. 
I see a memory increase of about 8 MB / second.
The out of memory point does not seem to be static. This time, memory consumption went up to 1246,7 MB.

Latest exception:
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.String.Concat(String str0, String str1, String str2)
   at TabularEditor.UI.SelectionHelper.Summary(IEnumerable`1 items, Boolean onlyTypeNames)
   at TabularEditor.UI.UIDeleteAction.OnUpdate(EventArgs e)
   at Crad.Windows.Forms.Actions.Action.DoUpdate()
   at Crad.Windows.Forms.Actions.ActionList.OnUpdate(EventArgs eventArgs)
   at Crad.Windows.Forms.Actions.ActionList.Application_Idle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.RunDialog(Form form)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at System.Windows.Forms.Form.ShowDialog()
   at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)
   at System.Windows.Forms.Control.WndProcException(Exception e)
   at System.Windows.Forms.Control.ControlNativeWindow.OnThreadException(Exception e)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.SendMessage(HandleRef hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.Control.SendMessage(Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.Control.ReflectMessageInternal(IntPtr hWnd, Message& m)
   at System.Windows.Forms.Control.WmNotify(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


```

**Comment by otykier** [comment]
Thanks for the additional details. Unfortunately, we're still not able to reproduce the issue. It seems that something in this specific model is causing the dependency detection algorithm to end up in an infinite loop, ultimately causing the OOM exception (note, TE2 is a 32 bit .NET application, so it doesn't matter that you have 3 GB or more available on the machine - the exception will happen at some arbitrary point before the application hits 2 GB of working memory).

It would be incredibly helpful if you can send us the model.bim file, or just a subset of the file that demonstrates the issue (we don't need partition or data source metadata - just tables, columns, relationships and measures). We're also happy to sign an NDA if needed. Please reach out to us at support@tabulareditor.com

**Comment by fmms** [comment]
thanks @otykier , I will try to align what I need to do to get the file sent to you.

**Comment by fmms** [comment]
Mail has been sent. 

![image](https://github.com/TabularEditor/TabularEditor/assets/908734/a6f4e12a-1849-49d0-90c9-7f82fbaa8c2b)

**Comment by fmms** [comment]
@otykier very much appreciated
